# Generated by Django 4.2 on 2024-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anonymity',
            field=models.BooleanField(default='True'),
        ),
    ]
