# Generated by Django 5.0.3 on 2024-03-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
